import type { Exercise } from "./gym-types";

export const EXPANDED_EXERCISES: Exercise[] = [
  // ==========================================
  // CHEST (חזה - 5 distinct exercises)
  // ==========================================
  {
    id: "ex-bench",
    name: "לחיצת חזה",
    englishName: "Bench Press",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "כתפיים"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל הבסיס המוביל לבניית כוח ומסה בחזה.",
    instructions: "שכבי על הספסל, אחזי במוט ברוחב מעט רחב מהכתפיים, הורידי באיטיות אל מרכז החזה ולחצי מעלה בנתיב יציב.",
    videoUrl: "",
    images: [],
    notes: "לשמור על שכמות מכווצות לאחור וקשת קלה בגב התחתון.",
    tips: "ללחוץ דרך העקבים ולשמור על מרפקים בזווית של כ-45 מעלות מהגוף.",
    searchTerms: ["בנץ", "בנץ פרס", "bench", "bench press", "לחיצה שטוחה", "מוט חזה", "חזה מוט"],
  },
  {
    id: "ex-incline-bench",
    name: "לחיצת חזה בשיפוע חיובי",
    englishName: "Incline Bench Press",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["כתף קדמית", "טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "לחיצה בשיפוע חיובי להתמקדות בסיבי החזה העליונים.",
    instructions: "הורידי את המשקוליות בצורה מבוקרת ולחצי מעלה בקו מעוגל קל.",
    videoUrl: "",
    images: [],
    notes: "זווית ספסל אידיאלית היא 30 מעלות למניעת עומס יתר על הכתפיים.",
    tips: "לשמור על מרפקים יציבים.",
    searchTerms: ["אינקליין", "incline bench", "חזה עליון", "שיפוע חיובי", "incline press"],
  },
  {
    id: "ex-db-bench",
    name: "לחיצת חזה עם משקוליות",
    englishName: "Dumbbell Chest Press",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "כתפיים"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "לחיצה יחידנית המאפשרת טווח תנועה מוגדל ועבודה שוויונית על שני צדי החזה.",
    instructions: "הורידי את המשקוליות לצדי החזה תוך מתיחה מלאה, ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים יציבים ולא לנעול בפתאומיות בשיא התנועה.",
    searchTerms: ["דאמבל בנץ", "dumbbell bench", "משקוליות חזה", "לחיצת משקוליות שטוחה"],
  },
  {
    id: "ex-pec-deck",
    name: "פרפר",
    englishName: "Chest Fly / Pec Deck",
    muscleGroup: "חזה",
    muscleGroups: ["חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל בידוד לחזה המעניק מתיחה חזקה ומתח אחיד בשריר החזה.",
    instructions: "שבי צמוד למשענת, אחזי בידיות וקרבי את הזרועות במרכז תוך כיווץ החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לכווץ חזק לשנייה אחת בשיא התנועה במרכז.",
    searchTerms: ["פק דק", "pec deck", "butterfly", "מכונת פרפר", "פרפר כבלים", "cable flyes", "קרוס אובר"],
  },
  {
    id: "ex-pushups",
    name: "שכיבות סמיכה",
    englishName: "Push-Ups",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית", "בטן"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "בטן"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "תרגיל משקל גוף קלאסי ואפקטיבי לחיזוק החזה, הכתפיים והטריצפס.",
    instructions: "הניחי כפות ידיים מעט רחבות מהכתפיים, רדי עד שהחזה כמעט נוגע ברצפה ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על גוף ישר בקו אחד (פלאנק) לאורך כל החזרות.",
    searchTerms: ["שכיבות סמיכה", "pushups", "push ups", "משקל גוף חזה"],
  },

  // ==========================================
  // BACK (גב - 6 distinct exercises)
  // ==========================================
  {
    id: "ex-lat-pulldown",
    name: "פולי עליון",
    englishName: "Lat Pulldown",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב", "גב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "כתף אחורית"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "תרגיל מפתח לפיתוח רוחב הגב בצורה מבוקרת ומותאמת משקל.",
    instructions: "אחזי במוט, שבי יציב ומשכי את המוט לכיוון החזה העליון תוך כיווץ השכמות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "להקפיד על חזה מורם ולא להישען אחורה מדי.",
    searchTerms: ["פולי עליון", "lat pulldown", "פולי רחב", "לאט פולדאון", "פולי"],
  },
  {
    id: "ex-pullups",
    name: "עליות מתח",
    englishName: "Pull-Ups",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "בטן"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "תרגיל הבסיס התנועתי הטוב ביותר לפיתוח רוחב הגב והגב הרחב.",
    instructions: "אחזי במוט המתח באחיזה עילית, משכי את החזה אל המוט והורידי באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למשוך דרך המרפקים ולמנוע נדנוד של הגוף.",
    searchTerms: ["מתח", "pullups", "pull ups", "עליות מתח", "מתח רחב", "גרביטרון"],
  },
  {
    id: "ex-row",
    name: "חתירה",
    englishName: "Seated Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "טרפזים", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "כתף אחורית"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "חתירה אופקית המעבה את מרכז הגב והשכמות.",
    instructions: "שבי מול הכבל עם ברכיים כפופות קלות, משכי את הידית אל הבטן התחתונה תוך הצמדת השכמות.",
    videoUrl: "",
    images: [],
    notes: "להקפיד לא להשתמש בתנופה מוגזמת של הגב.",
    tips: "למשוך דרך המרפקים ולא דרך כפות הידיים.",
    searchTerms: ["חתירה בישיבה", "seated row", "cable row", "פולי תחתונה", "חתירה כבלים", "חתירה במכונה"],
  },
  {
    id: "ex-barbell-row",
    name: "חתירה במוט",
    englishName: "Barbell Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "גב תחתון", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["גב תחתון", "המסטרינג"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל כוח מורכב רב-מפרקי המפתח את עובי וחוזק כל שרירי הגב.",
    instructions: "הטי את הגו קדימה בזווית 45 מעלות עם גב ישר, אחזי במוט ומשכי אל הטבור.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על גב ישר לחלוטין ולמנוע קשת גבית.",
    searchTerms: ["חתירה במוט", "barbell row", "bent over row", "חתירה בהטיית גו"],
  },
  {
    id: "ex-db-row",
    name: "חתירה עם משקולת יד",
    englishName: "Single-Arm Dumbbell Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "חתירה חד-צדדית המאפשרת מיקוד גבוה בכל צד בנפרד ללא עומס על הגב התחתון.",
    instructions: "הניחי ברך ויד על הספסל, משכי את המשקולת ביד השנייה אל האגן ושחררי במבוקר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למשוך את המשקולת לכיוון המותן ולא לכיוון החזה.",
    searchTerms: ["חתירה משקולת", "db row", "single arm row", "מסור משקולת"],
  },
  {
    id: "ex-hyperextension",
    name: "פשטת גו",
    englishName: "Back Extension",
    muscleGroup: "גב תחתון",
    muscleGroups: ["גב תחתון", "ישבן", "המסטרינג"],
    secondaryMuscles: ["ישבן"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל מצוין לחיזוק שרירי הזוקפים בגב התחתון, הישבן וההמסטרינג.",
    instructions: "הניחי ירכיים על הכריות, רדי קדימה בצורה מבוקרת והרמי את הגו חזרה לקו ישר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לפשוט את הגב מעבר לקו ישר בחלק העליון.",
    searchTerms: ["פשטת גו", "hyperextension", "back extension", "גב תחתון"],
  },

  // ==========================================
  // SHOULDERS (כתפיים - 4 distinct exercises)
  // ==========================================
  {
    id: "ex-ohp",
    name: "לחיצת כתפיים",
    englishName: "Shoulder Press",
    muscleGroup: "כתפיים",
    muscleGroups: ["כתפיים", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "בטן"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "תרגיל הכוח הבסיסי המרכזי לחיזוק ובניית כתפיים חזקות ועגולות.",
    instructions: "שבי או עמדי יציב, אחזי במשקולות/מוט בגובה הכתפיים ולחצי מעלה מעל הראש.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "בטן מהודקת וישבן מכווץ לשמירה על הגב התחתון.",
    searchTerms: ["אוברהד פרס", "ohp", "overhead press", "לחיצת כתפיים מוט", "פרס", "לחיצת כתפיים משקוליות", "db shoulder press"],
  },
  {
    id: "ex-lateral-raises",
    name: "הרחקת כתפיים",
    englishName: "Lateral Raises",
    muscleGroup: "כתף צדית",
    muscleGroups: ["כתף צדית", "כתפיים"],
    secondaryMuscles: ["טרפזים"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל המפתח המרכזי המעניק לכתפיים את המראה הרחב והמעוגל.",
    instructions: "עמדי יציב, הרמי את המשקוליות לצדדים בגובה הכתפיים בכפיפה קלה במרפק והורידי באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "להרים דרך המרפקים ולא להשתמש בתנופה של הגב.",
    searchTerms: ["הרחקת כתפיים", "lateral raises", "הרחקת זרועות", "כתף צדית", "הרחקת כתפיים בכבל"],
  },
  {
    id: "ex-facepull",
    name: "פייס פול",
    englishName: "Face Pull",
    muscleGroup: "כתף אחורית",
    muscleGroups: ["כתף אחורית", "טרפזים", "גב"],
    secondaryMuscles: ["טרפזים"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל קריטי לבריאות הכתפיים, היציבה וחיזוק הכתף האחורית.",
    instructions: "אחזי בחבל הפולי העליון, משכי את מרכז החבל לכיוון המצח תוך סיבוב חיצוני של הכתפיים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "ללכת עד הסוף ולכווץ את כתפיים לאחור.",
    searchTerms: ["פייס פול", "face pull", "facepull", "כבלים לפנים", "כתף אחורית"],
  },
  {
    id: "ex-shrugs-db",
    name: "הרמת שכמות",
    englishName: "Shrugs",
    muscleGroup: "טרפזים",
    muscleGroups: ["טרפזים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל ממוקד לפיתוח וחיזוק שרירי הטרפזים העליונים.",
    instructions: "החזיקי משקוליות לצדי הירכיים, הרמי שכמות מעלה לכיוון האוזניים, השהי לשנייה והורידי.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "תנועה אנכית ישרה מעלה ומטה בלבד ללא סיבוב כתפיים.",
    searchTerms: ["טרפזים", "shrugs", "הרמת שכמות"],
  },

  // ==========================================
  // BICEPS (ביצפס / יד קדמית - 3 distinct exercises)
  // ==========================================
  {
    id: "ex-curl",
    name: "כפיפת מרפקים",
    englishName: "Bicep Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל היד הקדמית הקלאסי והנפוץ ביותר לפיתוח שרירי הזרוע.",
    instructions: "עמדי יציב, החזיקי משקוליות לצדי הגוף, כפפי את המרפקים והרמי מעלה בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים צמודים לגוף ולמנוע נדנוד גב.",
    searchTerms: ["כפילת מרפקים", "כפיפת מרפקים", "dumbbell curl", "bicep curl", "יד קדמית משקוליות", "כפילת מוט", "ez bar curl"],
  },
  {
    id: "ex-hammer-curl",
    name: "כפיפת מרפקים פטישים",
    englishName: "Hammer Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "אחיזה ניטרלית (אגודלים מעלה) המפתחת את שריר הברכיאליס ומעבה את הזרוע והאמה.",
    instructions: "החזיקי משקוליות כשאגודלים פונים קדימה, כפפי את הזרוע מעלה ללא סיבוב כף היד.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פטישים", "hammer curl", "האמר קרל", "אחיזת פטיש"],
  },
  {
    id: "ex-preacher-curl",
    name: "כפיפת מרפקים בסקוט",
    englishName: "Preacher Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מוט W / EZ",
    description: "תרגיל בידוד קלאסי המונע תנופה של הגוף ומבודד את שיא השריר.",
    instructions: "הניחי את הזרועות על ספסל הסקוט, הורידי את המוט מבוקר ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לנעול מרפקים בפתאומיות בתחתית.",
    searchTerms: ["ספסל סקוט", "preacher curl", "פריצ'ר קרל", "כפילה בסקוט"],
  },

  // ==========================================
  // TRICEPS (טריצפס / יד אחורית - 3 distinct exercises)
  // ==========================================
  {
    id: "ex-tricep-pushdown",
    name: "פשיטת מרפקים בפולי",
    englishName: "Tricep Pushdown",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל היד האחורית הפופולרי ביותר לעיצוב וחיזוק זרוע אחורית.",
    instructions: "עמדי מול הפולי, דחפי את החבל/המוט מטה עד יישור מרפקים מלא ושחררי במבוקר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים קבועים וצמודים לצדי הגוף.",
    searchTerms: ["פולי חבל", "tricep pushdown", "rope pushdown", "יד אחורית חבל", "פשיטת מרפקים בפולי"],
  },
  {
    id: "ex-skull-crusher",
    name: "לחיצה צרפתית",
    englishName: "Skull Crusher",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מוט W / EZ",
    description: "תרגיל כוח מרכזי ליד האחורית המפעיל חזק את הראש הארוך של השריר.",
    instructions: "שכבי על ספסל, הורידי מוט/משקולות לכיוון המצח בכפיפת מרפקים בלבד ולחצי חזרה מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור מרפקים פונים מעלה ולא לתת להם לברוח לצדדים.",
    searchTerms: ["לחיצה צרפתית", "skull crusher", "סקאל קראשר", "פשטת מרפקים בשכיבה"],
  },
  {
    id: "ex-overhead-cable-ext",
    name: "פשיטת מרפקים מעל הראש",
    englishName: "Overhead Triceps Extension",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "מתיחה עמוקה לראש הארוך של הטריצפס מעל הראש.",
    instructions: "אחזי בחבל מעל הראש, כפפי ויישרי את המרפקים מעלה בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["overhead extension", "פולי מעל הראש", "יד אחורית מעל הראש"],
  },

  // ==========================================
  // QUADRICEPS (ארבע ראשי - 5 distinct exercises)
  // ==========================================
  {
    id: "ex-squat",
    name: "סקוואט",
    englishName: "Squat",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן", "גב תחתון"],
    secondaryMuscles: ["ישבן", "בטן"],
    category: "מורכב",
    equipment: "מוט",
    description: "מלך תרגילי הרגליים — תרגיל הבסיס העוצמתי ביותר לבניית פלג גוף תחתון.",
    instructions: "הניחי את המוט על הטרפזים או אחזי במשקולת מול החזה, רדי עם האגן אחורה ולמטה ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "דחיפה דרך מרכז כף הרגל ושמירה על חזה מורם.",
    searchTerms: ["סקוואט", "squat", "back squat", "סקואט מוט", "סקוואט על הגב", "גובלט סקוואט"],
  },
  {
    id: "ex-leg-press",
    name: "לחיצת רגליים",
    englishName: "Leg Press",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן"],
    secondaryMuscles: ["ישבן", "המסטרינג"],
    category: "מכונה",
    equipment: "מכונה",
    description: "תרגיל מורכב במכשיר המאפשר העמסת משקלים בצורה בטיחותית ויציבה.",
    instructions: "שבי במכונה, הניחי כפות רגליים ברוחב כתפיים, שחררי ניצרה ולחצי את המשטח מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לנעול ברכיים בפתאומיות בחלק העליון.",
    searchTerms: ["לחיצת רגליים", "leg press", "לג פרס", "מכונת רגליים"],
  },
  {
    id: "ex-leg-extension",
    name: "פשיטת ברך",
    englishName: "Leg Extension",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל הבידוד הבלעדי והמוביל לארבע ראשי לקבלת כיווץ ושריפה בשריר.",
    instructions: "שבי במכונה, יישרי את הברכיים מעלה תוך כיווץ חזק בשיא התנועה לשנייה אחת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "ירידה איטית ומבוקרת בחלק השלילי.",
    searchTerms: ["פשטת ברכיים", "פשיטת ברך", "leg extension", "פשטת ברך", "מכונת ארבע ראשי"],
  },
  {
    id: "ex-lunges-walking",
    name: "מכרעיים",
    englishName: "Lunges",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן", "המסטרינג"],
    secondaryMuscles: ["ישבן"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "צעדי מכרעיים המפתחים כוח, יציבות ושיווי משקל ברגליים.",
    instructions: "קחי צעד רחב קדימה, רדי עם הברך האחורית לכיוון הרצפה ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["לאנג'ים", "lunges", "walking lunges", "מכרעיים בהליכה", "לאנג'"],
  },
  {
    id: "ex-bulgarian-lunge",
    name: "מכרעיים בולגריים",
    englishName: "Bulgarian Split Squat",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן", "ארבע ראשי", "המסטרינג"],
    secondaryMuscles: ["ארבע ראשי"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "תרגיל חד-רגלי עוצמתי המבודד ומחזק את הישבן והארבע ראשי בצורה מורגשת.",
    instructions: "הניחי רגל אחת לאחור על ספסל, רדי עם הברך האחורית לכיוון הרצפה ולחצי מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "הטיית חזה קלה קדימה מחרפת ומגבירה עומס על הישבן.",
    searchTerms: ["בולגרי", "bulgarian split squat", "מכרעיים בולגריים", "סקוואט בולגרי"],
  },

  // ==========================================
  // HAMSTRINGS (המסטרינג / ירך אחורית - 3 distinct exercises)
  // ==========================================
  {
    id: "ex-rdl",
    name: "דדליפט רומני",
    englishName: "Romanian Deadlift (RDL)",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג", "ישבן", "גב תחתון"],
    secondaryMuscles: ["ישבן", "גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל המסטרינג וישבן עוצמתי המבוסס על ציר אגן (Hinge) ומתיחה עמוקה.",
    instructions: "אחזי במוט או במשקולות, קחי את האגן אחורנית תוך כפיפה קלה בברכיים והורידי לאורך הרגליים.",
    videoUrl: "",
    images: [],
    notes: "מתיחה מורגשת בהמסטרינג.",
    tips: "גב ישר לחלוטין לאורך כל התנועה.",
    searchTerms: ["אר דדליפט", "rdl", "romanian deadlift", "דדליפט רומני", "רומניאן"],
  },
  {
    id: "ex-lying-leg-curl",
    name: "כפיפת ברך",
    englishName: "Leg Curl",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג"],
    secondaryMuscles: ["תאומים"],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל בידוד מרכזי לירך האחורית במכונה בישיבה או בשכיבה.",
    instructions: "כפפי את הברכיים לכיוון הישבן תוך כיווץ חזק של ההמסטרינג ושחררי במבוקר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["כפילת ברכיים בשכיבה", "lying leg curl", "לג קרל בשכיבה", "כפיפת ברך בישיבה", "seated leg curl"],
  },
  {
    id: "ex-good-mornings",
    name: "גוד מורנינג",
    englishName: "Good Mornings",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג", "ישבן", "גב תחתון"],
    secondaryMuscles: ["גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל ציר אגן עם מוט על השכמות המכניס עומס מתיחה חזק להמסטרינג ולגב התחתון.",
    instructions: "הניחי מוט על הטרפזים, כפפי גו קדימה עם גב ישר על ידי דחיפת האגן אחורה, וחזרי לעמידה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["good mornings", "גוד מורנינג"],
  },

  // ==========================================
  // GLUTES (ישבן - 3 distinct exercises)
  // ==========================================
  {
    id: "ex-hipthrust",
    name: "היפ טראסט",
    englishName: "Hip Thrust",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן", "המסטרינג"],
    secondaryMuscles: ["המסטרינג", "ארבע ראשי"],
    category: "מורכב",
    equipment: "מוט",
    description: "התרגיל המנצח והיעיל ביותר לבניית כוח, נפח ועיצוב שרירי הישבן.",
    instructions: "הניחי גב עליון על ספסל, מוט/משקולת על האגן, הרמי את האגן מעלה וכווצי את הישבן בשיא הגובה.",
    videoUrl: "",
    images: [],
    notes: "לעצור לשנייה אחת בחלק העליון.",
    tips: "מבט קדימה וכיווץ מלא לשנייה בשיא ההרמה.",
    searchTerms: ["היפ טראסט", "hip thrust", "דחיקת אגן", "היפטרסט"],
  },
  {
    id: "ex-cable-kickback",
    name: "פשיטת ירך בכבל",
    englishName: "Cable Glute Kickback",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל בידוד פופולרי לעיצוב הישבן באמצעות רצועת קרסול בכבלים.",
    instructions: "חברי רצועה לקרסול בפולי התחתון, עמדי מול המכשיר ובעטי את הרגל לאחור תוך כיווץ הישבן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["קיקבק", "glute kickback", "פשטת ירך כבלים", "בעיטת ישבן"],
  },
  {
    id: "ex-hip-abduction-machine",
    name: "הרחקת ירכיים במכונה",
    englishName: "Hip Abduction",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן"],
    secondaryMuscles: [],
    category: "מכונה",
    equipment: "מכונה",
    description: "מכונת הרחקת ירכיים המיועדת לחיזוק הישבן הצידי.",
    instructions: "שבי במכונה, דחפי את הברכיים כלפי חוץ כנגד הכריות והחזירי באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["הרחקת ירכיים", "hip abduction", "מכונת ישבן צידי"],
  },

  // ==========================================
  // CALVES (תאומים - 1 distinct exercise)
  // ==========================================
  {
    id: "ex-standing-calf-raise",
    name: "הרמת עקבים",
    englishName: "Calf Raise",
    muscleGroup: "תאומים",
    muscleGroups: ["תאומים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל מפתח לפיתוח וחיזוק שרירי התאומים בעמידה או בישיבה.",
    instructions: "עמדי או שבי במכשיר, הורידי את העקבים למתיחה מלאה ולחצי מעלה בשיא הגובה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "עצירה של שנייה בתחתית למתיחה ושנייה בשיא העלייה.",
    searchTerms: ["תאומים בעמידה", "standing calf raise", "הרמת עקבים", "seated calf raise", "תאומים"],
  },

  // ==========================================
  // CORE / ABS (בטן וליבה - 4 distinct exercises)
  // ==========================================
  {
    id: "ex-plank",
    name: "פלאנק",
    englishName: "Plank",
    muscleGroup: "בטן",
    muscleGroups: ["בטן", "אלכסונים", "גב תחתון"],
    secondaryMuscles: ["כתפיים"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל ליבה סטאטי מצוין לשמירה על יציבות ואחזקת שרירי הבטן.",
    instructions: "החזיקי גוף ישר על האמות וקצות האצבעות תוך כיווץ חזק של הבטן והישבן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "גוף בקו ישר יחיד מהראש ועד העקבים.",
    searchTerms: ["פלאנק", "plank", "בטן סטטית"],
  },
  {
    id: "ex-crunches",
    name: "כפיפות בטן",
    englishName: "Crunches",
    muscleGroup: "בטן",
    muscleGroups: ["בטן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל בטן בסיסי קלאסי המבודד את השריר הישר הבטני.",
    instructions: "שכבי על הגב, ברכיים כפופות, הרמי את השכמות מהרצפה תוך כיווץ חזק בבטן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["כפיפות בטן", "crunches", "בטן קלאסי", "כפיפות בטן כבלים", "cable crunch"],
  },
  {
    id: "ex-hanging-leg-raise",
    name: "הרמת רגליים בתלייה",
    englishName: "Hanging Leg Raise",
    muscleGroup: "בטן",
    muscleGroups: ["בטן", "כופפי הירך"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל בטן מתקדם ואפקטיבי במיוחד לחלק התחתון של שריר הישר הבטני.",
    instructions: "היתלי על מוט מתח, הרמי את הרגליים ישרות או כפופות עד זווית 90 מעלות ומעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למנוע תנופה ונדנוד של הגוף.",
    searchTerms: ["הרמת רגליים במתח", "hanging leg raise", "בטן בתלייה"],
  },
  {
    id: "ex-russian-twists",
    name: "פיתולי גו",
    englishName: "Russian Twists",
    muscleGroup: "אלכסונים",
    muscleGroups: ["אלכסונים", "בטן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל אלכסונים וסיבוב גו בישיבה לחיזוק שרירי הדופן הצידית.",
    instructions: "שבי עם גו נטוי קלות לאחור, סובבי את כפות הידיים מצד לצד בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["רושיאן טוויסט", "russian twists", "פיתולים אלכסונים"],
  },

  // ==========================================
  // FULL BODY / COMPOUND (גוף מלא / דדליפט - 3 distinct exercises)
  // ==========================================
  {
    id: "ex-deadlift",
    name: "דדליפט",
    englishName: "Deadlift",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "גב תחתון", "המסטרינג", "ישבן", "גב"],
    secondaryMuscles: ["ארבע ראשי", "אמות"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל הכוח המקיף ביותר בגוף האדם המפעיל את השרשרת האחורית במלואה.",
    instructions: "עמדי מול המוט, אחזי ברוחב כתפיים, הרמי את המוט תוך דחיפת הרצפה ויישור האגן והגב.",
    videoUrl: "",
    images: [],
    notes: "גב ישר לחלוטין לאורך כל ההרמה.",
    tips: "",
    searchTerms: ["דדליפט", "deadlift", "conventional deadlift", "דדליפט מוט", "סומו דדליפט", "sumo deadlift"],
  },
  {
    id: "ex-kettlebell-swing",
    name: "סווינג עם קטלבל",
    englishName: "Kettlebell Swing",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "ישבן", "המסטרינג", "גב תחתון"],
    secondaryMuscles: ["כתפיים"],
    category: "מורכב",
    equipment: "קטלבל",
    description: "תרגיל כוח וסיבולת דינמי ומתפרץ לשרשרת האחורית ולכושר אירובי.",
    instructions: "הניפי את הקטלבל בין הרגליים ודחפי את האגן בעוצמה קדימה להנפת הקטלבל בגובה החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["קטלבל סווינג", "kettlebell swing", "סווינג קטלבל"],
  },
  {
    id: "ex-farmer-walk",
    name: "הליכת איכרים",
    englishName: "Farmer's Walk",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "אמות", "טרפזים", "בטן"],
    secondaryMuscles: ["כתפיים"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "הליכה עם משקולות כבדות בצדדים לחיזוק אחיזה, כתפיים, טרפזים ויציבות גוף.",
    instructions: "אחזי ב-2 משקולות כבדות, עמדי זקופה והתרכזי בהליכה יציבה בקו ישר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["הליכת איכרים", "farmer walk", "farmers carry", "אחיזה"],
  },
];
