import type { Exercise } from "./gym-types";

export const EXPANDED_EXERCISES: Exercise[] = [
  // ==========================================
  // CHEST (חזה - 18 exercises)
  // ==========================================
  {
    id: "ex-bench",
    name: "לחיצת חזה כנגד מוט",
    englishName: "Barbell Bench Press",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "כתפיים"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל הבסיס המוביל לבניית כוח ומסה בחזה העליון והמרכזי.",
    instructions: "שכב על הספסל, אחוז במוט ברוחב מעט רחב מהכתפיים, הורד באיטיות אל מרכז החזה ולחץ מעלה בנתיב יציב.",
    videoUrl: "",
    images: [],
    notes: "לשמור על שכמות מכווצות לאחור וקשת קלה בגב התחתון.",
    tips: "ללחוץ דרך העקבים ולשמור על מרפקים בזווית של כ-45 מעלות מהגוף.",
    searchTerms: ["בנץ", "בנץ פרס", "bench", "bench press", "לחיצה שטוחה", "מוט חזה"],
  },
  {
    id: "ex-incline-bench",
    name: "לחיצת חזה בשיפוע חיובי כנגד מוט",
    englishName: "Incline Barbell Bench Press",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["כתף קדמית", "טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "מוט",
    description: "לחיצה בשיפוע חיובי של 30–45 מעלות להתמקדות בסיבי החזה העליונים.",
    instructions: "הורד את המוט אל החלק העליון של החזה ולחץ מעלה בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "זווית ספסל אידיאלית היא 30 מעלות למניעת עומס יתר על הכתפיים.",
    searchTerms: ["אינקליין", "incline bench", "חזה עליון מוט", "שיפוע חיובי"],
  },
  {
    id: "ex-decline-bench",
    name: "לחיצת חזה בשיפוע שלילי כנגד מוט",
    englishName: "Decline Barbell Bench Press",
    muscleGroup: "חזה תחתון",
    muscleGroups: ["חזה תחתון", "חזה", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "מוט",
    description: "לחיצה בשיפוע שלילי להתמקדות בחלק התחתון והתחתון-חיצוני של החזה.",
    instructions: "הורד את המוט בצורה מבוקרת לחלק התחתון של החזה ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לוודא נעילת רגליים בטוחה בספסל השלילי.",
    searchTerms: ["דיקליין", "decline bench", "חזה תחתון", "שיפוע שלילי"],
  },
  {
    id: "ex-db-bench",
    name: "לחיצת חזה שטוחה עם משקוליות יד",
    englishName: "Flat Dumbbell Press",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "כתפיים"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "לחיצה יחידנית המאפשרת טווח תנועה מוגדל ועבודה שוויונית על שני צדי החזה.",
    instructions: "הורד את המשקוליות לצדי החזה תוך מתיחה מלאה, ולחץ מעלה עד מפגש קל של המשקוליות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים יציבים ולא לנעול בפתאומיות בשיא התנועה.",
    searchTerms: ["דאמבל בנץ", "dumbbell bench", "משקוליות חזה", "לחיצת משקוליות שטוחה"],
  },
  {
    id: "ex-incline-db-press",
    name: "לחיצת חזה בשיפוע חיובי עם משקוליות",
    englishName: "Incline Dumbbell Press",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["כתפיים", "טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "לחיצת משקוליות על ספסל נטוי להתמקד בחזה העליון עם מתיחה עמוקה.",
    instructions: "שב בשיפוע 30 מעלות, הורד את המשקוליות בצורה מבוקרת ולחץ מעלה בקו מעוגל קל.",
    videoUrl: "",
    images: [],
    notes: "שיפוע 30 מעלות מתמקד בחזה העליון.",
    tips: "",
    searchTerms: ["אינקליין דאמבל", "incline db press", "משקוליות שיפוע חיובי"],
  },
  {
    id: "ex-decline-db-press",
    name: "לחיצת חזה בשיפוע שלילי עם משקוליות",
    englishName: "Decline Dumbbell Press",
    muscleGroup: "חזה תחתון",
    muscleGroups: ["חזה תחתון", "חזה"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "תרגיל מורכב ממוקד לחזה התחתון באמצעות משקוליות יד.",
    instructions: "שכב בשיפוע שלילי, הורד את המשקוליות לאזור הפיטמות ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["decline db press", "שיפוע שלילי משקוליות"],
  },
  {
    id: "ex-db-flyes",
    name: "פרפר עם משקוליות בשכיבה",
    englishName: "Flat Dumbbell Flyes",
    muscleGroup: "חזה",
    muscleGroups: ["חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל בידוד לחזה המעניק מתיחה חזקה בסיבי שריר החזה.",
    instructions: "שכב על ספסל שטוח, פתח את הזרועות לצדדים בכפיפה קלה במרפקים והבא חזרה למרכז.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא להוריד את המשקוליות מעבר לקו הכתפיים למניעת עומס במפרק.",
    searchTerms: ["פרפר משקוליות", "dumbbell flyes", "flyes", "פרפר שטוח"],
  },
  {
    id: "ex-incline-db-flyes",
    name: "פרפר בשיפוע חיובי עם משקוליות",
    englishName: "Incline Dumbbell Flyes",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל בידוד ממוקד לחזה העליון בשיפוע חיובי.",
    instructions: "פתח את המשקוליות בשיפוע חיובי והבא אותן חזרה מעל מרכז החזה העליון.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["incline flyes", "פרפר שיפוע חיובי"],
  },
  {
    id: "ex-cable-flyes",
    name: "פרפר בכבלים (Cable Flyes)",
    englishName: "Cable Crossover / Cable Flyes",
    muscleGroup: "חזה",
    muscleGroups: ["חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "עבודה בכבלים המעניקה מתח מתמיד לאורך כל טווח התנועה בחזה.",
    instructions: "עמוד במרכז הקרוס-אובר, קח את הידיות קדימה בתנועת חיבוק תוך כיווץ חזק של החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "כיווץ מלא לשנייה אחת במפגש הידיים.",
    searchTerms: ["קרוס אובר", "cable crossover", "cable flyes", "פרפר כבלים", "פולי חזה"],
  },
  {
    id: "ex-low-cable-flyes",
    name: "פרפר בכבלים מנמוך לגבוה",
    englishName: "Low to High Cable Flyes",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "משיכת כבלים מתחתית המכשיר כלפי מעלה להדגשת סיבי החזה העליון.",
    instructions: "עמוד במרכז, אחוז בידיות התחתונות ומשוך מעלה ופנימה אל מול החזה העליון.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["low cable fly", "כבלים נמוך לגבוה", "חזה עליון כבלים"],
  },
  {
    id: "ex-high-cable-flyes",
    name: "פרפר בכבלים מגבוה לנמוך",
    englishName: "High to Low Cable Flyes",
    muscleGroup: "חזה תחתון",
    muscleGroups: ["חזה תחתון", "חזה"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "משיכת כבלים מגובה העיניים מטה אל מרכז החזה התחתון.",
    instructions: "אחוז בכבלים העליונים, דחף מעט גו קדימה וקשר את הידיות למטה ומלפנים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["high to low cable fly", "כבלים גבוה לנמוך", "חזה תחתון כבלים"],
  },
  {
    id: "ex-pec-deck",
    name: "פרפר במכונה (Pec Deck / Butterfly)",
    englishName: "Pec Deck Machine",
    muscleGroup: "חזה",
    muscleGroups: ["חזה"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל בידוד יציב ובטוח למיקוד מלא בשריר החזה ללא צורך בייצוב המשקל.",
    instructions: "שב צמוד למשענת, אחוז בידיות וקרב את הזרועות במרכז תוך כיווץ החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פק דק", "pec deck", "butterfly", "מכונת פרפר"],
  },
  {
    id: "ex-chest-press-machine",
    name: "לחיצת חזה במכונה (Chest Press Machine)",
    englishName: "Machine Chest Press",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מכונה",
    equipment: "מכונה",
    description: "לחיצת חזה מיוצגת במכונה המתאימה לעבודה כבדה ובטוחה.",
    instructions: "שב עם גב צמוד, אחוז בידיות ולחץ קדימה עד יישור מבוקר של הזרועות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["מכונת לחיצת חזה", "chest press machine"],
  },
  {
    id: "ex-incline-machine-press",
    name: "לחיצת חזה עליון במכונה",
    englishName: "Incline Machine Chest Press",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "מכונה",
    equipment: "מכונה",
    description: "לחיצה זוויתית במכונה המבודדת את החזה העליון במסלול תנועה קבוע.",
    instructions: "שב במכונה הזוויתית, אחוז בידיות ולחץ באלכסון מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["incline machine press", "מכונת חזה עליון"],
  },
  {
    id: "ex-pushups",
    name: "שכיבות סמיכה (Push-Ups)",
    englishName: "Push-Ups",
    muscleGroup: "חזה",
    muscleGroups: ["חזה", "טריצפס (יד אחורית)", "כתף קדמית", "בטן"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "בטן"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "תרגיל משקל גוף קלאסי ואפקטיבי לחיזוק החזה, הכתפיים והטריצפס.",
    instructions: "הנח כפות ידיים מעט רחבות מהכתפיים, רד עד שהחזה כמעט נוגע ברצפה ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על גוף ישר בקו אחד (פלאנק) לאורך כל החזרות.",
    searchTerms: ["שכיבות סמיכה", "pushups", "push ups", "משקל גוף חזה"],
  },
  {
    id: "ex-incline-pushups",
    name: "שכיבות סמיכה בשיפוע חיובי (ידיים על ספסל)",
    englishName: "Incline Push-Ups",
    muscleGroup: "חזה תחתון",
    muscleGroups: ["חזה תחתון", "חזה"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "שכיבות סמיכה כשהידיים מונחות על משטח מוגבה, המקלות על העומס וממקדות את החזה התחתון.",
    instructions: "הנח ידיים על ספסל, רד אל הספסל ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["incline pushups", "שכיבות סמיכה שיפוע חיובי"],
  },
  {
    id: "ex-decline-pushups",
    name: "שכיבות סמיכה בשיפוע שלילי (רגליים על ספסל)",
    englishName: "Decline Push-Ups",
    muscleGroup: "חזה עליון",
    muscleGroups: ["חזה עליון", "חזה"],
    secondaryMuscles: ["כתף קדמית"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "שכיבות סמיכה כשהרגליים מורמות על ספסל, להגברת העומס על החזה העליון.",
    instructions: "הנח רגליים על ספסל וידיים על הרצפה, רד בצורה מבוקרת ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["decline pushups", "שכיבות סמיכה רגליים מורמות"],
  },
  {
    id: "ex-dips-chest",
    name: "מקבילים בדגש חזה (Chest Dips)",
    englishName: "Chest Dips",
    muscleGroup: "חזה תחתון",
    muscleGroups: ["חזה תחתון", "חזה", "טריצפס (יד אחורית)", "כתף קדמית"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "עליות מקבילים ברכוב נטוי קדימה למיקוד בחזה התחתון והמרכזי.",
    instructions: "הטה את הגוף קדימה בזווית 30 מעלות, כפוף מרפקים עד 90 מעלות ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "הטיית הגוף קדימה מעבירה את העומס מהטריצפס לחזה.",
    searchTerms: ["מקבילים", "dips", "chest dips", "מקבילים חזה"],
  },

  // ==========================================
  // BACK (גב - 20 exercises)
  // ==========================================
  {
    id: "ex-pullups",
    name: "עליות מתח (Pull-Ups)",
    englishName: "Pull-Ups",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "בטן"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "תרגיל הבסיס התנועתי הטוב ביותר לפיתוח רוחב הגב והגב הרחב (Latissimus Dorsi).",
    instructions: "אחוז במוט המתח באחיזה עילית רחבה מהכתפיים, משוך את החזה אל המוט והורד באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למשוך דרך המרפקים ולמנוע נדנוד של הגוף.",
    searchTerms: ["מתח", "pullups", "pull ups", "עליות מתח", "מתח רחב"],
  },
  {
    id: "ex-chinups",
    name: "עליות מתח באחיזה תחתית (Chin-Ups)",
    englishName: "Chin-Ups",
    muscleGroup: "גב",
    muscleGroups: ["גב", "ביצפס (יד קדמית)", "גב רחב"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "מתח באחיזה תחתית (סופינציה) המשלב עבודה חזקה של הביצפס יחד עם הגב.",
    instructions: "אחוז במוט כפות ידיים פונות אליך ברוחב כתפיים, משוך את הסנטר מעל המוט.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["צ'ין אפס", "chin ups", "מתח בנות", "מתח אחיזה תחתית"],
  },
  {
    id: "ex-assisted-pullup",
    name: "מתח במכשיר גרביטרון (Assisted Pull-Up)",
    englishName: "Assisted Pull-Up Machine",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב", "גב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מכונה",
    equipment: "מכונה",
    description: "תרגיל מתח מודרך עם משקל פלטה מעכב המקל על המשקל ומאפשר למידת מתח הדרגתית.",
    instructions: "עמוד או ברך על המשטח, אחוז במוט העליון ומשוך מעלה בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["גרביטרון", "assisted pullup", "מתח במכונה"],
  },
  {
    id: "ex-lat-pulldown",
    name: "פולי עליון באחיזה רחבה (Lat Pulldown)",
    englishName: "Lat Pulldown",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב", "גב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "כתף אחורית"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "תרגיל מפתח לפיתוח רוחב הגב בצורה מבוקרת ומותאמת משקל.",
    instructions: "אחוז במוט הרחב, שב יציב ומשוך את המוט לכיוון החזה העליון תוך כיווץ השכמות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "להקפיד לחזה מורם ולא להישען אחורה מדי.",
    searchTerms: ["פולי עליון", "lat pulldown", "פולי רחב", "לאט פולדאון"],
  },
  {
    id: "ex-close-grip-lat-pulldown",
    name: "פולי עליון באחיזה צרה (Close Grip Pulldown)",
    englishName: "Close-Grip Lat Pulldown",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב", "גב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "משיכת פולי עליון עם ידית V צרה המאפשרת טווח מתיחה עמוק בחלק התחתון של הגב הרחב.",
    instructions: "אחוז בידית ה-V הצרה, משוך אל מרכז החזה העליון ושחרר בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פולי צר", "close grip pulldown", "ידית V פולי"],
  },
  {
    id: "ex-reverse-grip-pulldown",
    name: "פולי עליון באחיזה הפוכה (Reverse Grip Pulldown)",
    englishName: "Reverse Grip Lat Pulldown",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "משיכת פולי באחיזה תחתית (סופינציה) להגברת מעורבות הזרועות והחלק התחתון של הגב הרחב.",
    instructions: "אחוז במוט באחיזה תחתית ברוחב כתפיים ומשוך אל שקע החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["reverse grip pulldown", "פולי אחיזה תחתית"],
  },
  {
    id: "ex-row",
    name: "חתירה בכבלים בישיבה (Seated Cable Row)",
    englishName: "Seated Cable Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "טרפזים", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)", "כתף אחורית"],
    category: "מורכב",
    equipment: "פולי / כבלים",
    description: "חתירה אופקית המעבה את מרכז הגב והשכמות.",
    instructions: "שב מול הכבל עם ברכיים כפופות קלות, משוך את הידית אל הבטן התחתונה תוך הצמדת השכמות.",
    videoUrl: "",
    images: [],
    notes: "להקפיד לא להשתמש בתנופה מוגזמת של הגב.",
    tips: "למשוך דרך המרפקים ולא דרך כפות הידיים.",
    searchTerms: ["חתירה בישיבה", "seated row", "cable row", "פולי תחתונה", "חתירה כבלים"],
  },
  {
    id: "ex-single-arm-cable-row",
    name: "חתירה בכבל ביד אחת (Single Arm Cable Row)",
    englishName: "Single-Arm Cable Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "חתירה חד-צדדית בכבלים המאפשרת טווח סחיטה וכיווץ עמוק בכל צד.",
    instructions: "עמוד או שב מול הפולי, משוך ביד אחת אל המותן תוך סיבוב קל של הגו.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["single arm cable row", "חתירה כבל יד אחת"],
  },
  {
    id: "ex-barbell-row",
    name: "חתירה בהטיית גו כנגד מוט (Bent-Over Barbell Row)",
    englishName: "Bent-Over Barbell Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "גב תחתון", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["גב תחתון", "המסטרינג"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל כוח מורכב רב-מפרקי המפתח את עובי וחוזק כל שרירי הגב.",
    instructions: "הטה את הגו קדימה בזווית 45 מעלות עם גב ישר, אחוז במוט ומשוך אל הטבור.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על גב ישר לחלוטין ולמנוע קשת גבית.",
    searchTerms: ["חתירה במוט", "barbell row", "bent over row", "חתירה בהטיית גו"],
  },
  {
    id: "ex-pendlay-row",
    name: "חתירת פנדליי מהרצפה (Pendlay Row)",
    englishName: "Pendlay Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "גב תחתון"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "מוט",
    description: "חתירת מוט ממתח מלא על הרצפה בכל חזרה, המפתחת כוח מתפרץ חזק בגב.",
    instructions: "הטה גו מקביל לרצפה, משוך את המוט מעלה מהרצפה אל החזה התחתון והורד חזרה לרצפה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פנדליי", "pendlay row", "חתירה מהרצפה"],
  },
  {
    id: "ex-db-row",
    name: "חתירה עם משקולת יד בהשענות על ספסל",
    englishName: "Single-Arm Dumbbell Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "ביצפס (יד קדמית)"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "חתירה חד-צדדית המאפשרת מיקוד גבוה בכל צד בנפרד ללא עומס על הגב התחתון.",
    instructions: "הנח ברך ויד על הספסל, משוך את המשקולת ביד השנייה אל האגן ושחרר במבוקר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למשוך את המשקולת לכיוון המותן ולא לכיוון החזה.",
    searchTerms: ["חתירה משקולת", "db row", "single arm row", "מסור משקולת"],
  },
  {
    id: "ex-tbar-row",
    name: "חתירה במוט T-Bar",
    englishName: "T-Bar Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "טרפזים"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מורכב",
    equipment: "מוט",
    description: "חתירה בעמידה עם מוט ייעודי או פינת קיר המאפשרת העמסת משקל כבד בצורה יציבה.",
    instructions: "עמוד מעל המוט, הטה גו קדימה, אחוז בידית הצרה ומשוך אל החזה התחתון.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["טי בר", "tbar row", "t-bar row", "חתירת טי בר"],
  },
  {
    id: "ex-straight-arm-pulldown",
    name: "פשטת זרועות בפולי בעמידה (Straight-Arm Pulldown)",
    englishName: "Straight-Arm Pulldown",
    muscleGroup: "גב רחב",
    muscleGroups: ["גב רחב"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "בטן"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל בידוד מעולה לגב הרחב ללא מעורבות של הביצפס.",
    instructions: "עמוד מול הפולי העליון, אחוז במוט בזרועות כמעט ישרות ודחף אותו מטה אל הירכיים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לכווץ את הגב הרחב בחלק התחתון ולא לכפוף את המרפקים.",
    searchTerms: ["סטרייט ארם", "straight arm pulldown", "פולי זרועות ישרות"],
  },
  {
    id: "ex-chest-supported-row",
    name: "חתירה במכונה עם תמיכה לחזה",
    englishName: "Chest-Supported Machine Row",
    muscleGroup: "גב",
    muscleGroups: ["גב", "גב רחב", "טרפזים"],
    secondaryMuscles: ["ביצפס (יד קדמית)"],
    category: "מכונה",
    equipment: "מכונה",
    description: "חתירה יציבה במכונה המבטלת לחץ מהגב התחתון ומתמקדת נטו בשרירי הגב.",
    instructions: "השען את החזה על הכרית, אחוז בידיות ומשוך לאחור תוך הידוק השכמות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["chest supported row", "חתירה במכונה", "מכונת חתירה"],
  },
  {
    id: "ex-facepull",
    name: "פייס פול בכבלים (Face Pull)",
    englishName: "Cable Face Pull",
    muscleGroup: "כתף אחורית",
    muscleGroups: ["כתף אחורית", "טרפזים", "גב"],
    secondaryMuscles: ["טרפזים"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל קריטי לבריאות הכתפיים, היציבה וחיזוק הכתף האחורית והסובבים.",
    instructions: "אחוז בחבל הפולי העליון, משוך את מרכז החבל לכיוון המצח תוך סיבוב חיצוני של הכתפיים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לסיים את התנועה כשהידיים בצורת W לצד הראש.",
    searchTerms: ["פייס פול", "face pull", "facepull", "כבלים לפנים"],
  },
  {
    id: "ex-hyperextension",
    name: "פשטת גו על ספסל 45 מעלות (Hyperextension)",
    englishName: "Back Extension / Hyperextension",
    muscleGroup: "גב תחתון",
    muscleGroups: ["גב תחתון", "ישבן", "המסטרינג"],
    secondaryMuscles: ["ישבן"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל מצוין לחיזוק שרירי הזוקפים בגב התחתון, הישבן וההמסטרינג.",
    instructions: "הנח ירכיים על הכריות, רד קדימה בצורה מבוקרת והרם את הגו חזרה לקו ישר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לפשוט את הגב מעבר לקו ישר בחלק העליון.",
    searchTerms: ["פשטת גו", "hyperextension", "back extension", "גב תחתון"],
  },
  {
    id: "ex-shrugs-barbell",
    name: "הרמת שכמות כנגד מוט (Barbell Shrugs)",
    englishName: "Barbell Shrugs",
    muscleGroup: "טרפזים",
    muscleGroups: ["טרפזים", "גב"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "מוט",
    description: "תרגיל ממוקד לפיתוח העובי והגובה של שרירי הטרפזים העליונים.",
    instructions: "עמוד זקוף, החזק מוט מול הירכיים והרם את השכמות מעלה לכיוון האוזניים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למנוע סיבוב של הכתפיים — תנועה ישרה מעלה ומטה בלבד.",
    searchTerms: ["טרפזים", "shrugs", "barbell shrugs", "הרמת שכמות"],
  },
  {
    id: "ex-shrugs-db",
    name: "הרמת שכמות עם משקוליות יד (Dumbbell Shrugs)",
    englishName: "Dumbbell Shrugs",
    muscleGroup: "טרפזים",
    muscleGroups: ["טרפזים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "הרמת שכמות עם משקוליות לצדי הגוף לאחיזה טבעית ונוחה יותר.",
    instructions: "החזק משקוליות לצדי הירכיים, הרם שכמות מעלה, השהה לשנייה והורד.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["db shrugs", "טרפזים משקוליות"],
  },

  // ==========================================
  // SHOULDERS (כתפיים - 16 exercises)
  // ==========================================
  {
    id: "ex-ohp",
    name: "לחיצת כתפיים בעמידה כנגד מוט (Overhead Press)",
    englishName: "Barbell Overhead Press (OHP)",
    muscleGroup: "כתפיים",
    muscleGroups: ["כתפיים", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["טריצפס (יד אחורית)", "בטן"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל הכוח הבסיסי המרכזי לפלג הגוף העליון ולחיזוק הכתפיים והטרפזים.",
    instructions: "עמוד יציב, אחוז במוט בגובה החזה העליון ולחץ מעלה בקו ישר מעל הראש.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "בטן מהודקת וישבן מכווץ לשמירה על הגב התחתון.",
    searchTerms: ["אוברהד פרס", "ohp", "overhead press", "לחיצת כתפיים מוט", "פרס בעמידה"],
  },
  {
    id: "ex-db-shoulder-press",
    name: "לחיצת כתפיים בישיבה עם משקוליות",
    englishName: "Seated Dumbbell Shoulder Press",
    muscleGroup: "כתפיים",
    muscleGroups: ["כתפיים", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "תרגיל פופולרי ונפוץ לבניית נפח ומסה בכתפיים בצורה מאוזנת ויציבה.",
    instructions: "שב על ספסל זקוף (90 מעלות), החזק את המשקוליות בגובה הכתפיים ולחץ מעלה מעל הראש.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["לחיצת כתפיים משקוליות", "db shoulder press", "דאמבל פרס כתפיים"],
  },
  {
    id: "ex-arnold-press",
    name: "לחיצת ארנולד (Arnold Press)",
    englishName: "Arnold Press",
    muscleGroup: "כתפיים",
    muscleGroups: ["כתפיים", "כתף קדמית", "כתף צדית"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "גרסת לחיצת כתפיים ייחודית עם סיבוב כפות הידיים המפעילה את כל שלושת ראשי הכתף.",
    instructions: "התחל כשהמשקוליות מול החזה באחיזה תחתית, ולחץ מעלה תוך סיבוב כפות הידיים חצי סיבוב.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["ארנולד פרס", "arnold press", "לחיצת ארנולד"],
  },
  {
    id: "ex-machine-shoulder-press",
    name: "לחיצת כתפיים במכונה (Machine Shoulder Press)",
    englishName: "Machine Shoulder Press",
    muscleGroup: "כתפיים",
    muscleGroups: ["כתפיים", "כתף קדמית", "טריצפס (יד אחורית)"],
    secondaryMuscles: ["טריצפס (יד אחורית)"],
    category: "מכונה",
    equipment: "מכונה",
    description: "לחיצת כתפיים יציבה ומבודדת במכונה המאפשרת מיקוד מלא ועבודה בטיחותית.",
    instructions: "שב במכונה, אחוז בידיות בגובה הכתפיים ולחץ מעלה בצורה רציפה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["מכונת כתפיים", "machine shoulder press"],
  },
  {
    id: "ex-lateral-raises",
    name: "הרחקת זרועות לצדדים עם משקוליות",
    englishName: "Dumbbell Lateral Raises",
    muscleGroup: "כתף צדית",
    muscleGroups: ["כתף צדית", "כתפיים"],
    secondaryMuscles: ["טרפזים"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל המפתח המרכזי המעניק לכתפיים את המראה הרחב והעגול (תלת-ממדי).",
    instructions: "עמוד יציב, הרם את המשקוליות לצדדים בגובה הכתפיים בכפיפה קלה במרפק והורד באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "להרים דרך המרפקים ולא להשתמש בתנופה של הגב.",
    searchTerms: ["הרחקת כתפיים", "lateral raises", "הרחקת זרועות", "כתף צדית משקוליות"],
  },
  {
    id: "ex-cable-lateral-raise",
    name: "הרחקת זרוע לצד בכבל (Cable Lateral Raise)",
    englishName: "Cable Lateral Raise",
    muscleGroup: "כתף צדית",
    muscleGroups: ["כתף צדית", "כתפיים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "הרחקת כתף בכבל המעניקה מתח קבוע גם בחלק התחתון של התנועה.",
    instructions: "אחוז בכבל התחתון מאחורי הגב או מלפנים, והרם את הזרוע לצד עד גובה הכתף.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["הרחקת כתף כבלים", "cable lateral raise", "כבלים כתף צדית"],
  },
  {
    id: "ex-front-raise",
    name: "הרמת זרועות לפנים עם משקוליות",
    englishName: "Dumbbell Front Raise",
    muscleGroup: "כתף קדמית",
    muscleGroups: ["כתף קדמית", "כתפיים"],
    secondaryMuscles: ["חזה עליון"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל בידוד ממוקד לראש הקדמי של הכתף.",
    instructions: "הרם את המשקולת לפנים עד גובה העיניים באופן מבוקר והורד באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["front raise", "הרמת זרועות לפנים", "כתף קדמית"],
  },
  {
    id: "ex-rear-delt-flyes",
    name: "פרפר הפוך לכתף אחורית במשקוליות",
    englishName: "Rear Delt Dumbbell Flyes",
    muscleGroup: "כתף אחורית",
    muscleGroups: ["כתף אחורית", "כתפיים"],
    secondaryMuscles: ["טרפזים"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל בידוד בהטיית גו לפיתוח הראש האחורי של הכתף.",
    instructions: "הטה גו קדימה, פתח את המשקוליות לצדדים תוך הובלה עם המרפקים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["rear delt flyes", "כתף אחורית משקוליות", "פרפר הפוך"],
  },
  {
    id: "ex-reverse-pec-deck",
    name: "פרפר הפוך במכונה (Reverse Pec Deck)",
    englishName: "Reverse Pec Deck Machine",
    muscleGroup: "כתף אחורית",
    muscleGroups: ["כתף אחורית", "כתפיים"],
    secondaryMuscles: ["טרפזים"],
    category: "מכונה",
    equipment: "מכונה",
    description: "תרגיל נוח ויציב במכונה לבידוד מוחלט של הכתף האחורית.",
    instructions: "שב מול מכונת ה-Pec Deck, אחוז בידיות ופרוס את הזרועות לאחור.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["reverse pec deck", "פרפר הפוך מכונה", "פק דק הפוך"],
  },

  // ==========================================
  // BICEPS (ביצפס / יד קדמית - 14 exercises)
  // ==========================================
  {
    id: "ex-curl",
    name: "כפילת מרפקים בעמידה עם משקוליות",
    englishName: "Standing Dumbbell Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "תרגיל היד הקדמית הקלאסי והנפוץ ביותר לפיתוח שרירי הזרוע.",
    instructions: "עמוד יציב, החזק משקוליות לצדי הגוף, כפוף את המרפקים והרם מעלה תוך סופינציה (סיבוב כף היד).",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים צמודים לגוף ולמנוע נדנוד גב.",
    searchTerms: ["כפילת מרפקים", "dumbbell curl", "bicep curl", "יד קדמית משקוליות"],
  },
  {
    id: "ex-barbell-curl",
    name: "כפילת מרפקים כנגד מוט ישר",
    englishName: "Barbell Bicep Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "מוט",
    description: "תרגיל העמסת המשקל המרכזי לביצפס להגדלת המסה והכוח בזרועות.",
    instructions: "אחוז במוט באחיזה תחתית ברוחב כתפיים, הרם את המוט אל הכתפיים בתנועה מעגלית מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["מוט ישר יד קדמית", "barbell curl", "כפילת מוט"],
  },
  {
    id: "ex-ez-bar-curl",
    name: "כפילת מרפקים עם מוט W (EZ-Bar)",
    englishName: "EZ-Bar Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "מוט W / EZ",
    description: "עבודה עם מוט W המפחיתה עומס מפרקי משרש כף היד והאמה.",
    instructions: "אחוז בחלק הנטוי של מוט ה-EZ, כפוף מרפקים והרם את המוט בצורה יציבה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["מוט W", "ez bar curl", "מוט איזי", "כפילת מרפקים W"],
  },
  {
    id: "ex-hammer-curl",
    name: "כפילת מרפקים אחיזת פטיש (Hammer Curl)",
    englishName: "Dumbbell Hammer Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)", "אמות"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "אחיזה ניטרלית (אגודלים מעלה) המפתחת את שריר הברכיאליס ומעבה את הזרוע והאמה.",
    instructions: "החזק משקוליות כשאגודלים פונים קדימה, כפוף את הזרוע מעלה ללא סיבוב כף היד.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פטישים", "hammer curl", "האמר קרל", "אחיזת פטיש"],
  },
  {
    id: "ex-incline-db-curl",
    name: "כפילת מרפקים בשיפוע חיובי (Incline DB Curl)",
    englishName: "Incline Dumbbell Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "ישיבה בשיפוע המעניקה מתיחה עמוקה לראש הארוך של הביצפס.",
    instructions: "שב על ספסל נטוי 45 מעלות, תן לזרועות להיות תלויות לאחור וכפוף את המרפקים מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["incline db curl", "אינקליין קרל", "יד קדמית שיפוע חיובי"],
  },
  {
    id: "ex-preacher-curl",
    name: "כפילת מרפקים בסקוט (Preacher Curl)",
    englishName: "Preacher Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מוט W / EZ",
    description: "תרגיל בידוד קלאסי המונע תנופה של הגוף ומבודד את שיא השריר (Peak).",
    instructions: "הנח את הזרועות על ספסל הסקוט (Preacher Bench), הורד את המוט כמעט עד הסוף ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לנעול מרפקים בפתאומיות בתחתית.",
    searchTerms: ["ספסל סקוט", "preacher curl", "פריצ'ר קרל", "כפילה בסקוט"],
  },
  {
    id: "ex-concentration-curl",
    name: "כפילת מרפקים מרוכזת (Concentration Curl)",
    englishName: "Concentration Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "כפילת מרפקים בישיבה כשהמרפק נשען על הירך הפנימית לבידוד מוחלט.",
    instructions: "שב על ספסל, השען מרפק אל פנים הירך וכפוף את המשקולת לכיוון החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["concentration curl", "כפילה מרוכזת"],
  },
  {
    id: "ex-cable-bicep-curl",
    name: "כפילת מרפקים בכבלים (Cable Bicep Curl)",
    englishName: "Cable Bicep Curl",
    muscleGroup: "ביצפס (יד קדמית)",
    muscleGroups: ["ביצפס (יד קדמית)"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל כבלים המעניק מתח אחיד ורציף לאורך כל טווח הכפילה.",
    instructions: "אחוז במוט הפולי התחתון, כפוף מרפקים מעלה ושחרר באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["cable curl", "פולי יד קדמית", "כבלים ביצפס"],
  },

  // ==========================================
  // TRICEPS (טריצפס / יד אחורית - 14 exercises)
  // ==========================================
  {
    id: "ex-tricep-pushdown",
    name: "פשטת מרפקים בפולי עם חבל (Rope Pushdown)",
    englishName: "Rope Tricep Pushdown",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל היד האחורית הפופולרי ביותר לעיצוב וחיזוק הראשי הצידי והמדיאלי.",
    instructions: "עמוד מול הפולי, דחף את החבל מטה עד יישור מרפקים מלא ופרוס את החבל בצדדים בתחתית.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור על מרפקים קבועים וצמודים לצדי הגוף.",
    searchTerms: ["פולי חבל", "tricep pushdown", "rope pushdown", "יד אחורית חבל"],
  },
  {
    id: "ex-bar-pushdown",
    name: "פשטת מרפקים בפולי עם מוט ישר",
    englishName: "Straight Bar Tricep Pushdown",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "פשטת מרפקים בפולי עם מוט קשיח המאפשר העמסת משקל כבד בצורה יציבה.",
    instructions: "אחוז במוט הפולי באחיזה עילית, לחץ את המוט מטה עד יישור מלא.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["bar pushdown", "פולי מוט יד אחורית"],
  },
  {
    id: "ex-skull-crusher",
    name: "לחיצה צרפתית בשכיבה (Skull Crusher)",
    englishName: "Lying Triceps Extension / Skull Crusher",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מוט W / EZ",
    description: "תרגיל כוח מרכזי ליד האחורית המפעיל חזק את הראש הארוך של השריר.",
    instructions: "שכב על ספסל, הורד מוט EZ לכיוון המצח בכפיפת מרפקים בלבד ולחץ חזרה מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לשמור מרפקים פונים מעלה ולא לתת להם לברוח לצדדים.",
    searchTerms: ["לחיצה צרפתית", "skull crusher", "סקאל קראשר", "פשטת מרפקים בשכיבה"],
  },
  {
    id: "ex-overhead-cable-ext",
    name: "פשטת מרפקים מעל הראש בכבל (Overhead Cable Extension)",
    englishName: "Overhead Cable Triceps Extension",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "מתיחה עמוקה לראש הארוך של הטריצפס באמצעות פולי כבלים.",
    instructions: "עמוד עם הגב לפולי, אחוז בחבל מעל הראש, כפוף ויישר את המרפקים מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["overhead extension", "פולי מעל הראש", "יד אחורית מעל הראש"],
  },
  {
    id: "ex-overhead-db-ext",
    name: "פשטת מרפקים מעל הראש עם משקולת יד",
    englishName: "Seated Overhead Dumbbell Extension",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקוליות יד",
    description: "פשטת מרפקים בישיבה עם משקולת יד יחידה המוחזקת בשתי הידיים מעל הראש.",
    instructions: "שב זקוף, החזק משקולת מעל הראש בשתי ידיים, הורד מאחורי העורף ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["overhead db extension", "משקולת מעל הראש יד אחורית"],
  },
  {
    id: "ex-close-grip-bench",
    name: "לחיצת חזה באחיזה צרה (Close-Grip Bench Press)",
    englishName: "Close-Grip Bench Press",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)", "חזה", "כתף קדמית"],
    secondaryMuscles: ["חזה"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל מורכב כבד המאפשר העמסת משקל רב על שריר הטריצפס.",
    instructions: "אחוז במוט ברוחב כתפיים (לא צר מדי), הורד אל החזה ולחץ מעלה תוך הצמדת מרפקים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["close grip bench", "אחיזה צרה בנץ", "לחיצה צרה"],
  },
  {
    id: "ex-dips-triceps",
    name: "מקבילים בדגש יד אחורית (Tricep Dips)",
    englishName: "Triceps Dips",
    muscleGroup: "טריצפס (יד אחורית)",
    muscleGroups: ["טריצפס (יד אחורית)", "חזה", "כתף קדמית"],
    secondaryMuscles: ["חזה"],
    category: "מורכב",
    equipment: "משקל גוף",
    description: "עליות מקבילים בגוף זקוף למיקוד מירבי בטריצפס.",
    instructions: "החזק את הגוף זקוף אנכית, כפוף מרפקים לאחור ל-90 מעלות ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "שמירה על גוף זקוף מעבירה את העומס אל הטריצפס.",
    searchTerms: ["מקבילים יד אחורית", "tricep dips"],
  },

  // ==========================================
  // QUADRICEPS (ארבע ראשי - 16 exercises)
  // ==========================================
  {
    id: "ex-squat",
    name: "סקואט כנגד מוט (Barbell Back Squat)",
    englishName: "Barbell Back Squat",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן", "גב תחתון"],
    secondaryMuscles: ["ישבן", "בטן"],
    category: "מורכב",
    equipment: "מוט",
    description: "מלך תרגילי הרגליים — תרגיל הבסיס העוצמתי ביותר לבניית פלג גוף תחתון.",
    instructions: "הנח את המוט על הטרפזים, רד עם האגן אחורה ולמטה עד זווית 90 מעלות ומטה, ולחץ חזרה מעלה.",
    videoUrl: "",
    images: [],
    notes: 'חגורת גב מעל 100 ק"ג.',
    tips: "דחיפה דרך מרכז כף הרגל ושמירה על חזה מורם.",
    searchTerms: ["סקוואט", "squat", "back squat", "סקואט מוט", "סקוואט על הגב"],
  },
  {
    id: "ex-front-squat",
    name: "סקואט קדמי (Front Squat)",
    englishName: "Barbell Front Squat",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "בטן"],
    secondaryMuscles: ["ישבן", "גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "סקואט כשהמוט מונח על הכתפיים הקדמיות, הממקד עומס רב על הארבע ראשי והבטן.",
    instructions: "הנח מוט מול הכתפיים, שמור מרפקים גבוהים, רד בסקוואט עמוק ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["פרונט סקוואט", "front squat", "סקוואט קדמי"],
  },
  {
    id: "ex-leg-press",
    name: "לחיצת רגליים במכונה (Leg Press)",
    englishName: "Leg Press Machine",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן"],
    secondaryMuscles: ["ישבן", "המסטרינג"],
    category: "מכונה",
    equipment: "מכונה",
    description: "תרגיל מורכב במכשיר המאפשר העמסת משקלים כבדים בבטיחות מלאה.",
    instructions: "שב במכונה, הנח כפות רגליים ברוחב כתפיים, שחרר ניצרה ולחץ את המשטח מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "לא לנעול ברכיים בפתאומיות בחלק העליון.",
    searchTerms: ["לחיצת רגליים", "leg press", "לג פרס", "מכונת רגליים"],
  },
  {
    id: "ex-hack-squat",
    name: "האק סקואט במכונה (Hack Squat)",
    englishName: "Hack Squat Machine",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן"],
    secondaryMuscles: ["ישבן"],
    category: "מכונה",
    equipment: "מכונה",
    description: "תרגיל סקואט זוויתי במכונה המעניק גירוי ממוקד ועוצמתי לארבע ראשי.",
    instructions: "השען גב על המשטח, רד לזווית 90 מעלות בברכיים ולחץ מעלה דרך העקבים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["האק סקוואט", "hack squat", "האק סקואט"],
  },
  {
    id: "ex-leg-extension",
    name: "פשטת ברכיים במכונה (Leg Extension)",
    englishName: "Leg Extension Machine",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל הבידוד הבלעדי והמוביל לארבע ראשי לקבלת כיווץ ושריפה בשריר.",
    instructions: "שב במכונה, ישר את הברכיים מעלה תוך כיווץ חזק בשיא התנועה לשנייה אחת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "ירידה איטית ומבוקרת בחלק השלילי.",
    searchTerms: ["פשטת ברכיים", "leg extension", "פשטת ברך", "מכונת ארבע ראשי"],
  },
  {
    id: "ex-goblet-squat",
    name: "סקואט גובלט עם משקולת יד (Goblet Squat)",
    englishName: "Goblet Squat",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן", "בטן"],
    secondaryMuscles: ["ישבן"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "סקואט נגיש ונוח כשהמשקולת מוחזקת מול החזה, מעולה ללמידת טכניקה.",
    instructions: "החזק משקולת צמודה לחזה, רד בסקואט עמוק בין הברכיים ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["גובלט סקוואט", "goblet squat", "סקוואט משקולת"],
  },
  {
    id: "ex-lunges-walking",
    name: "מכרעיים בהליכה (Walking Lunges)",
    englishName: "Walking Lunges",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן", "המסטרינג"],
    secondaryMuscles: ["ישבן"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "צעדי מכרעיים דינמיים המפתחים כוח, יציבות ושיווי משקל ברגליים.",
    instructions: "קח צעד רחב קדימה, רד עם הברך האחורית לכיוון הרצפה ועבור לצעד הבא.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["לאנג'ים", "lunges", "walking lunges", "מכרעיים בהליכה"],
  },
  {
    id: "ex-smith-squat",
    name: "סקואט בסמית' משין (Smith Machine Squat)",
    englishName: "Smith Machine Squat",
    muscleGroup: "ארבע ראשי",
    muscleGroups: ["ארבע ראשי", "ישבן"],
    secondaryMuscles: ["ישבן"],
    category: "מכונה",
    equipment: "סמית' משין",
    description: "סקואט במסלול קבוע ויציב במכשיר הסמית', המפחית צורך בייצוב וממקד עומס ברגליים.",
    instructions: "הנח את מוט הסמית' על הגב, רד ל-90 מעלות ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["smith squat", "סקוואט בסמית"],
  },

  // ==========================================
  // HAMSTRINGS (המסטרינג / ירך אחורית - 14 exercises)
  // ==========================================
  {
    id: "ex-rdl",
    name: "דדליפט רומני כנגד מוט (Romanian Deadlift)",
    englishName: "Romanian Deadlift (RDL)",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג", "ישבן", "גב תחתון"],
    secondaryMuscles: ["ישבן", "גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל המסטרינג וישבן עוצמתי המבוסס על ציר אגן (Hinge) ומתיחה עמוקה.",
    instructions: "אחוז במוט, קח את האגן אחורנית תוך כפיפה קלה בברכיים והורד את המוט לאורך הרגליים.",
    videoUrl: "",
    images: [],
    notes: "מתיחה מורגשת בהמסטרינג.",
    tips: "גב ישר לחלוטין לאורך כל התנועה.",
    searchTerms: ["אר דדליפט", "rdl", "romanian deadlift", "דדליפט רומני", "רומניאן"],
  },
  {
    id: "ex-db-rdl",
    name: "דדליפט רומני עם משקוליות יד",
    englishName: "Dumbbell Romanian Deadlift",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג", "ישבן"],
    secondaryMuscles: ["גב תחתון"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "דדליפט רומני נוח ונגיש עם משקוליות יד המאפשר נתיב משקל טבעי לצדי הרגליים.",
    instructions: "החזק משקוליות מול הירכיים, קח אגן אחורה והורד בצמוד לרגליים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["db rdl", "דדליפט רומני משקוליות"],
  },
  {
    id: "ex-lying-leg-curl",
    name: "כפילת ברכיים בשכיבה במכונה (Lying Leg Curl)",
    englishName: "Lying Leg Curl",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג"],
    secondaryMuscles: ["תאומים"],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל בידוד מרכזי לירך האחורית במכונה ייעודית.",
    instructions: "שכב על הבטן, כפוף את הברכיים לכיוון הישבן תוך כיווץ חזק של ההמסטרינג.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["כפילת ברכיים בשכיבה", "lying leg curl", "לג קרל בשכיבה"],
  },
  {
    id: "ex-seated-leg-curl",
    name: "כפילת ברכיים בישיבה במכונה (Seated Leg Curl)",
    englishName: "Seated Leg Curl",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "כפילת ברכיים בישיבה המעניקה מתיחה וכיווץ מעולים במצב מפרקי יציב.",
    instructions: "שב במכונה, הידק את הכרית מעל הברכיים וכפוף את הרגליים כלפי מטה לאחור.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["seated leg curl", "כפילת ברכיים בישיבה", "לג קרל בישיבה"],
  },
  {
    id: "ex-good-mornings",
    name: "גוד מורנינג כנגד מוט (Good Mornings)",
    englishName: "Barbell Good Mornings",
    muscleGroup: "המסטרינג",
    muscleGroups: ["המסטרינג", "ישבן", "גב תחתון"],
    secondaryMuscles: ["גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל ציר אגן עם מוט על השכמות המכניס עומס מתיחה חזק להמסטרינג ולגב התחתון.",
    instructions: "הנח מוט על הטרפזים, כפוף גו קדימה עם גב ישר על ידי דחיפת האגן אחורה, וחזור לעמידה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["good mornings", "גוד מורנינג"],
  },

  // ==========================================
  // GLUTES (ישבן - 14 exercises)
  // ==========================================
  {
    id: "ex-hipthrust",
    name: "דחיקת אגן כנגד מוט (Hip Thrust)",
    englishName: "Barbell Hip Thrust",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן", "המסטרינג"],
    secondaryMuscles: ["המסטרינג", "ארבע ראשי"],
    category: "מורכב",
    equipment: "מוט",
    description: "התרגיל המנצח והיעיל ביותר לבניית כוח, נפח ועיצוב שרירי הישבן.",
    instructions: "הנח גב עליון על ספסל, מוט על האגן, הרם את האגן מעלה וכווץ את הישבן בשיא הגובה.",
    videoUrl: "",
    images: [],
    notes: "לעצור לשנייה אחת בחלק העליון.",
    tips: "מבט קדימה וכיווץ מלא לשנייה בשיא ההרמה.",
    searchTerms: ["היפ טראסט", "hip thrust", "דחיקת אגן", "היפטרסט"],
  },
  {
    id: "ex-db-hipthrust",
    name: "דחיקת אגן עם משקולת יד",
    englishName: "Dumbbell Hip Thrust",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן", "המסטרינג"],
    secondaryMuscles: [],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "גרסת היפ-טראסט קלה ונגישה עם משקולת יד כבדה על האגן.",
    instructions: "שכב עם גב עליון על הספסל, החזק משקולת על האגן והרם אל קו ישר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["db hip thrust", "היפ טראסט משקולת"],
  },
  {
    id: "ex-bulgarian-lunge",
    name: "מכרעיים בולגריים (Bulgarian Split Squat)",
    englishName: "Bulgarian Split Squat",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן", "ארבע ראשי", "המסטרינג"],
    secondaryMuscles: ["ארבע ראשי"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "תרגיל חד-רגלי עוצמתי המבודד ומחזק את הישבן והארבע ראשי בצורה מורגשת.",
    instructions: "הנח רגל אחת לאחור על ספסל, רד עם הברך האחורית לכיוון הרצפה ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "הטיית חזה קלה קדימה מחרפת ומגבירה עומס על הישבן.",
    searchTerms: ["בולגרי", "bulgarian split squat", "מכרעיים בולגריים", "סקוואט בולגרי"],
  },
  {
    id: "ex-cable-kickback",
    name: "פשטת ירך בכבל לאחור (Cable Glute Kickback)",
    englishName: "Cable Glute Kickback",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל בידוד פופולרי לעיצוב הישבן באמצעות רצועת קרסול בכבלים.",
    instructions: "חבר רצועה לקרסול בפולי התחתון, עמוד מול המכשיר ובעט את הרגל לאחור תוך כיווץ הישבן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["קיקבק", "glute kickback", "פשטת ירך כבלים", "בעיטת ישבן"],
  },
  {
    id: "ex-hip-abduction-machine",
    name: "הרחקת ירכיים במכונה (Hip Abduction)",
    englishName: "Seated Hip Abduction Machine",
    muscleGroup: "ישבן",
    muscleGroups: ["ישבן"],
    secondaryMuscles: [],
    category: "מכונה",
    equipment: "מכונה",
    description: "מכונת הרחקת ירכיים המיועדת לחיזוק הישבן הצידי (Gluteus Medius).",
    instructions: "שב במכונה, דחף את הברכיים כלפי חוץ כנגד הכריות והחזר באיטיות.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["הרחקת ירכיים", "hip abduction", "מכונת ישבן צידי"],
  },

  // ==========================================
  // CALVES (תאומים - 8 exercises)
  // ==========================================
  {
    id: "ex-standing-calf-raise",
    name: "הרמת עקבים בעמידה במכונה (Standing Calf Raise)",
    englishName: "Standing Calf Raise",
    muscleGroup: "תאומים",
    muscleGroups: ["תאומים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "תרגיל מפתח לפיתוח שריר התאומים (Gastrocnemius) בעמידה.",
    instructions: "עמוד על קצות האצבעות, הורד את העקבים למתיחה מלאה ולחץ מעלה בשיא הגובה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "עצירה של שנייה בתחתית למתיחה ושנייה בשיא העלייה.",
    searchTerms: ["תאומים בעמידה", "standing calf raise", "הרמת עקבים"],
  },
  {
    id: "ex-seated-calf-raise",
    name: "הרמת עקבים בישיבה במכונה (Seated Calf Raise)",
    englishName: "Seated Calf Raise",
    muscleGroup: "תאומים",
    muscleGroups: ["תאומים"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "מכונה",
    description: "הרמת עקבים בישיבה הממיינת ומבודדת את שריר הסוליאוס (Soleus).",
    instructions: "שב במכונה, הנח את הכרית על הברכיים, הרם והורד את העקבים בטווח מלא.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["תאומים בישיבה", "seated calf raise"],
  },
  {
    id: "ex-leg-press-calf-raise",
    name: "הרמת עקבים בלחיצת רגליים (Leg Press Calf Raise)",
    englishName: "Leg Press Calf Raise",
    muscleGroup: "תאומים",
    muscleGroups: ["תאומים"],
    secondaryMuscles: [],
    category: "מכונה",
    equipment: "מכונה",
    description: "הרמת עקבים המתבצעת על קצה משטח בלחיצת הרגליים.",
    instructions: "הנח קצות אצבעות על תחתית המשטח, פשוט וכפוף את השרש כף הרגל.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["leg press calf raise", "תאומים בלג פרס"],
  },

  // ==========================================
  // CORE / ABS (בטן וליבה - 18 exercises)
  // ==========================================
  {
    id: "ex-plank",
    name: "פלאנק סטטי (Plank)",
    englishName: "Plank",
    muscleGroup: "בטן",
    muscleGroups: ["בטן", "אלכסונים", "גב תחתון"],
    secondaryMuscles: ["כתפיים"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל ליבה סטאטי מצוין לשמירה על יציבות ואחזקת שרירי הבטן.",
    instructions: "החזק גוף ישר על האמות וקצות האצבעות תוך כיווץ חזק של הבטן והישבן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "גוף בקו ישר יחיד מהראש ועד העקבים.",
    searchTerms: ["פלאנק", "plank", "בטן סטטית"],
  },
  {
    id: "ex-hanging-leg-raise",
    name: "הרמת רגליים בתלייה (Hanging Leg Raise)",
    englishName: "Hanging Leg Raise",
    muscleGroup: "בטן",
    muscleGroups: ["בטן", "כופפי הירך"],
    secondaryMuscles: ["אמות"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל בטן מתקדם ואפקטיבי במיוחד לחלק התחתון של שריר הישר הבטני.",
    instructions: "הנתלה על מוט מתח, הרם את הרגליים ישרות או כפופות עד זווית 90 מעלות ומעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "למנוע תנופה ונדנוד של הגוף.",
    searchTerms: ["הרמת רגליים במתח", "hanging leg raise", "בטן בתלייה"],
  },
  {
    id: "ex-cable-crunch",
    name: "כפיפות בטן בכבלים (Cable Crunch)",
    englishName: "Cable Crunch / Rope Crunch",
    muscleGroup: "בטן",
    muscleGroups: ["בטן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "פולי / כבלים",
    description: "תרגיל בטן מעולה בכבלים המאפשר העמסת התנגדות מותאמת אישית.",
    instructions: "רד על הברכיים מול הפולי העליון, החזק בחבל לצד הראש וכפוף את הגו לכיוון הברכיים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["כפיפות בטן כבלים", "cable crunch", "בטן פולי"],
  },
  {
    id: "ex-ab-wheel",
    name: "גלגלת בטן (Ab Wheel Rollout)",
    englishName: "Ab Wheel Rollout",
    muscleGroup: "בטן",
    muscleGroups: ["בטן", "גב תחתון"],
    secondaryMuscles: ["כתפיים", "גב רחב"],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל ליבה מתקדם ומאתגר במיוחד המחזק את הבטן והגב התחתון.",
    instructions: "עמוד על הברכיים, גלגל את הגלגלת קדימה בצורה מבוקרת עד כמעט מתיחה מלאה וחזור.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["גלגלת בטן", "ab wheel", "rollout"],
  },
  {
    id: "ex-crunches",
    name: "כפיפות בטן על מזרן (Crunches)",
    englishName: "Abdominal Crunches",
    muscleGroup: "בטן",
    muscleGroups: ["בטן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל בטן בסיסי קלאסי המבודד את השריר הישר הבטני.",
    instructions: "שכב על הבטן, ברכיים כפופות, הרם את השכמות מהרצפה תוך כיווץ חזק בבטן.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["כפיפות בטן", "crunches", "בטן קלאסי"],
  },
  {
    id: "ex-russian-twists",
    name: "פיתולי גו רוסיים (Russian Twists)",
    englishName: "Russian Twists",
    muscleGroup: "אלכסונים",
    muscleGroups: ["אלכסונים", "בטן"],
    secondaryMuscles: [],
    category: "בידוד",
    equipment: "משקל גוף",
    description: "תרגיל אלכסונים וסיבוב גו בישיבה לחיזוק שרירי הדופן הצידית.",
    instructions: "שב עם גו נטוי קלות לאחור, סובב את כפות הידיים או משקולת מצד לצד בצורה מבוקרת.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["רושיאן טוויסט", "russian twists", "פיתולים אלכסונים"],
  },

  // ==========================================
  // FULL BODY / COMPOUND (גוף מלא / דדליפט - 10 exercises)
  // ==========================================
  {
    id: "ex-deadlift",
    name: "דדליפט קלאסי כנגד מוט (Conventional Deadlift)",
    englishName: "Barbell Conventional Deadlift",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "גב תחתון", "המסטרינג", "ישבן", "גב"],
    secondaryMuscles: ["ארבע ראשי", "אמות"],
    category: "מורכב",
    equipment: "מוט",
    description: "תרגיל הכוח המקיף ביותר בגוף האדם המפעיל את השרשרת האחורית במלואה.",
    instructions: "עמוד מול המוט, אחוז ברוחב כתפיים, הרם את המוט תוך דחיפת הרצפה ויישור האגן והגב.",
    videoUrl: "",
    images: [],
    notes: "גב ישר לחלוטין לאורך כל ההרמה.",
    tips: "",
    searchTerms: ["דדליפט", "deadlift", "conventional deadlift", "דדליפט מוט"],
  },
  {
    id: "ex-sumo-deadlift",
    name: "דדליפט סומו כנגד מוט (Sumo Deadlift)",
    englishName: "Sumo Deadlift",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "ישבן", "מקרבים", "ארבע ראשי"],
    secondaryMuscles: ["גב תחתון"],
    category: "מורכב",
    equipment: "מוט",
    description: "דדליפט בעמידה רחבה (סומו) המפחית זווית כפוף גו וממקד עומס רב בישבן ובמקרבים.",
    instructions: "עמוד בעמידה רחבה מאוד, אחוז במוט באחיזה צרה מלפנים ולחץ מעלה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["סומו דדליפט", "sumo deadlift"],
  },
  {
    id: "ex-trap-bar-deadlift",
    name: "דדליפט מוט משושה (Trap Bar Deadlift)",
    englishName: "Trap Bar / Hex Bar Deadlift",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "ארבע ראשי", "ישבן", "גב תחתון"],
    secondaryMuscles: ["המסטרינג"],
    category: "מורכב",
    equipment: "מוט",
    description: "גרסת דדליפט בטוחה ונוחה במיוחד עם מוט טראפ-בר המפחיתה עומס מהגב התחתון.",
    instructions: "עמוד במרכז הטרפ-בר, אחוז בידיות הצדדיות ולחץ מעלה דרך העקבים.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["טראפ בר", "trap bar deadlift", "hex bar", "דדליפט משושה"],
  },
  {
    id: "ex-kettlebell-swing",
    name: "סווינג עם קטלבל (Kettlebell Swing)",
    englishName: "Kettlebell Swing",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "ישבן", "המסטרינג", "גב תחתון"],
    secondaryMuscles: ["כתפיים"],
    category: "מורכב",
    equipment: "קטלבל",
    description: "תרגיל כוח וסיבולת דינמי ומתפרץ לשרשרת האחורית ולכושר אירובי.",
    instructions: "הנף את הקטלבל בין הרגליים ודחוף את האגן בעוצמה קדימה להנפת הקטלבל בגובה החזה.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["קטלבל סווינג", "kettlebell swing", "סווינג קטלבל"],
  },
  {
    id: "ex-farmer-walk",
    name: "הליכת איכרים (Farmer's Walk)",
    englishName: "Farmer's Walk",
    muscleGroup: "גוף מלא",
    muscleGroups: ["גוף מלא", "אמות", "טרפזים", "בטן"],
    secondaryMuscles: ["כתפיים"],
    category: "מורכב",
    equipment: "משקוליות יד",
    description: "הליכה עם משקולות כבדות בצדדים לחיזוק אחיזה, כתפיים, טרפזים ויציבות גוף.",
    instructions: "אחוז ב-2 משקולות כבדות, עמוד זקוף והתרכז בהליכה יציבה בקו ישר.",
    videoUrl: "",
    images: [],
    notes: "",
    tips: "",
    searchTerms: ["הליכת איכרים", "farmer walk", "farmers carry", "אחיזה"],
  },
];
