/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as SessionWorkoutIdRouteImport } from './routes/session.$workoutId'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts.$workoutId'
import { Route as NutritionFoodsIndexRouteImport } from './routes/nutrition.foods.index'
import { Route as NutritionFoodsFoodIdRouteImport } from './routes/nutrition.foods.$foodId'
import { Route as ProgramsProgramIdDayIdRouteImport } from './routes/programs.$programId.$dayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionWorkoutIdRoute = SessionWorkoutIdRouteImport.update({
  id: '/session/$workoutId',
  path: '/session/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionFoodsIndexRoute = NutritionFoodsIndexRouteImport.update({
  id: '/nutrition/foods/',
  path: '/nutrition/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionFoodsFoodIdRoute = NutritionFoodsFoodIdRouteImport.update({
  id: '/nutrition/foods/$foodId',
  path: '/nutrition/foods/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdDayIdRoute = ProgramsProgramIdDayIdRouteImport.update({
  id: '/$dayId',
  path: '/$dayId',
  getParentRoute: () => ProgramsProgramIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/nutrition/foods/': typeof NutritionFoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/exercises': typeof ExercisesIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/nutrition/foods': typeof NutritionFoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/nutrition/foods/': typeof NutritionFoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/exercises/'
    | '/nutrition/'
    | '/programs/'
    | '/workouts/'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/nutrition/foods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/exercises'
    | '/nutrition'
    | '/programs'
    | '/workouts'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/nutrition/foods'
  id:
    | '__root__'
    | '/'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/exercises/'
    | '/nutrition/'
    | '/programs/'
    | '/workouts/'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/nutrition/foods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRouteWithChildren
  SessionWorkoutIdRoute: typeof SessionWorkoutIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  NutritionFoodsFoodIdRoute: typeof NutritionFoodsFoodIdRoute
  NutritionFoodsIndexRoute: typeof NutritionFoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$workoutId': {
      id: '/session/$workoutId'
      path: '/session/$workoutId'
      fullPath: '/session/$workoutId'
      preLoaderRoute: typeof SessionWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/foods/': {
      id: '/nutrition/foods/'
      path: '/nutrition/foods'
      fullPath: '/nutrition/foods/'
      preLoaderRoute: typeof NutritionFoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/foods/$foodId': {
      id: '/nutrition/foods/$foodId'
      path: '/nutrition/foods/$foodId'
      fullPath: '/nutrition/foods/$foodId'
      preLoaderRoute: typeof NutritionFoodsFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/$dayId': {
      id: '/programs/$programId/$dayId'
      path: '/$dayId'
      fullPath: '/programs/$programId/$dayId'
      preLoaderRoute: typeof ProgramsProgramIdDayIdRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
  }
}

interface ProgramsProgramIdRouteChildren {
  ProgramsProgramIdDayIdRoute: typeof ProgramsProgramIdDayIdRoute
}

const ProgramsProgramIdRouteChildren: ProgramsProgramIdRouteChildren = {
  ProgramsProgramIdDayIdRoute: ProgramsProgramIdDayIdRoute,
}

const ProgramsProgramIdRouteWithChildren =
  ProgramsProgramIdRoute._addFileChildren(ProgramsProgramIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRouteWithChildren,
  SessionWorkoutIdRoute: SessionWorkoutIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  NutritionFoodsFoodIdRoute: NutritionFoodsFoodIdRoute,
  NutritionFoodsIndexRoute: NutritionFoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
